experiment_name: adam-0.0003
seed: 42
augmentation: False
rot_range: 90
zoom_range: 0.2
vertical_flip: True
batch_size: 4
filter_list: [64,128,256,512]
kernel_size: 3
batch_norm: True
epochs: 100
patience: 10
loss: focal
alpha: 0.5
optimizer: 'adam'
lr: 0.0003
lr_scheduler: False
class_weights: 'weighted'
