experiment_name: debug
seed: 42
augmentation: False
rot_range: 45
vertical_flip: True
zoom_range: 0.2
batch_size: 1
model:
  filter_list: [4,8,16,32]
  kernel_size: 3
epochs: 5
patience: 2
loss: focal
alpha: 0.5
optimizer: 'lookahead'
lr: 0.0003
lr_scheduler: False
class_weights: 'balanced'
