experiment_name: sgd
seed: 42
augmentation: True
rot_range: 90
zoom_range: 0.2
vertical_flip: True
batch_size: 32
filter_list: [64,128,256,512]
kernel_size: 3
batch_norm: False
epochs: 100
patience: 10
loss: focal
alpha: 0.5
optimizer: 'sgd'
lr: 'default'
lr_scheduler: False
class_weights: 'balanced'
