experiment_name: XE-BN-weighted
seed: 42
augmentation: False
rot_range: 45
zoom_range: 0.2
batch_size: 1
filter_list: [64,128,256,512]
kernel_size: 3
batch_norm: True
epochs: 300
patience: 10
loss: cross-entropy
alpha: 0.5
optimizer: 'adam'
lr: 'default'
lr_scheduler: False
class_weights: 'balanced'
