experiment_name: xgb-cnn-lstm-mitbih
model_id: transfer_model
base_model_path: ./cnn-lstm-mitbih/cnn-lstm-mitbih.h5
base_weights_path: ./cnn-lstm-mitbih/cnn-lstm-mitbih-weights.h5
dataset: mitbih
val_split_size: 0.2
debug: False
