experiment_name: xgb-lstm-mitbih
model_id: transfer_model
base_model_path: ./lstm-mitbih/lstm-mitbih.h5
base_weights_path: ./lstm-mitbih/lstm-mitbih-weights.h5
dataset: mitbih
val_split_size: 0.2
debug: False
