experiment_name: xgb-cnn-lstm-ptbdb
model_id: transfer_model
base_model_path: ./cnn-lstm-ptbdb/cnn-lstm-ptbdb.h5
base_weights_path: ./cnn-lstm-ptbdb/cnn-lstm-ptbdb-weights.h5
dataset: ptbdb
val_split_size: 0.2
debug: False
