experiment_name: transfer-xgb-lstm-ptbdb
model_id: transfer_model
base_model_path: ./results/lstm-mitbih/lstm-mitbih.h5
base_weights_path: ./results/lstm-mitbih/lstm-mitbih-weights.h5
dataset: ptbdb
val_split_size: 0.2
debug: False
