experiment_name: frozen-transfer-lstm-ptbdb
model_id: transfer-model
base_model_path: ./results/lstm-mitbih/lstm-mitbih.h5
base_weights_path: ./results/lstm-mitbih/lstm-mitbih-weights.h5
freeze-weights: True
dataset: ptbdb
upsample: True
val_split_size: 0.2
batch_size: 128
epochs: 100
debug: False
patience: 3
lr_schuduler: True
